# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getNcpp <- function(type, nc, ncf, jj, nmix, pmix, intervals, openval, cc, PIAJ) {
    .Call(`_openCR_getNcpp`, type, nc, ncf, jj, nmix, pmix, intervals, openval, cc, PIAJ)
}

getNBcpp <- function(n, x, nc, jj, openval, cc, PIAJ, intervals) {
    .Call(`_openCR_getNBcpp`, n, x, nc, jj, openval, cc, PIAJ, intervals)
}

getDcpp <- function(type, nc, jj, nmix, pmix, intervals, openval, cc, PIAJ) {
    .Call(`_openCR_getDcpp`, type, nc, jj, nmix, pmix, intervals, openval, cc, PIAJ)
}

makegkcpp <- function(cc, kk, mm, detectfn, sigmai, openval, traps, mask) {
    .Call(`_openCR_makegkcpp`, cc, kk, mm, detectfn, sigmai, openval, traps, mask)
}

PCH1cpp <- function(type, x, nc, jj, cumss, nmix, openval0, cc0, PIA0, PIAJ, intervals) {
    .Call(`_openCR_PCH1cpp`, type, x, nc, jj, cumss, nmix, openval0, cc0, PIA0, PIAJ, intervals)
}

PCH1secrcpp <- function(type, x, nc, jj, cumss, kk, mm, openval0, cc0, PIA0, PIAJ, gk0, binomN, Tsk, intervals, moveargsi, movemodel, usermodel, kn, kernel, mqarray, cellsize) {
    .Call(`_openCR_PCH1secrcpp`, type, x, nc, jj, cumss, kk, mm, openval0, cc0, PIA0, PIAJ, gk0, binomN, Tsk, intervals, moveargsi, movemodel, usermodel, kn, kernel, mqarray, cellsize)
}

PCH0secrjcpp <- function(type, x, nc, jj, cumss, kk, mm, openval0, cc0, PIA0, gk0, binomN, Tsk) {
    .Call(`_openCR_PCH0secrjcpp`, type, x, nc, jj, cumss, kk, mm, openval0, cc0, PIA0, gk0, binomN, Tsk)
}

pradelloglikcpp <- function(type, w, nc, jj, nmix, openval, cc, PIAJ, intervals) {
    .Call(`_openCR_pradelloglikcpp`, type, w, nc, jj, nmix, openval, cc, PIAJ, intervals)
}

prwicpp <- function(type, n, x, nc, jj, cumss, nmix, w, fi, li, openval, cc, PIA, PIAJ, intervals, CJSp1) {
    .Call(`_openCR_prwicpp`, type, n, x, nc, jj, cumss, nmix, w, fi, li, openval, cc, PIA, PIAJ, intervals, CJSp1)
}

prwisecrcpp <- function(type, n, x, nc, jj, kk, mm, nmix, cumss, w, fi, li, gk, openval, cc, PIA, PIAJ, binomN, Tsk, intervals, moveargsi, CJSp1, movemodel, usermodel, kn, kernel, mqarray, cellsize) {
    .Call(`_openCR_prwisecrcpp`, type, n, x, nc, jj, kk, mm, nmix, cumss, w, fi, li, gk, openval, cc, PIA, PIAJ, binomN, Tsk, intervals, moveargsi, CJSp1, movemodel, usermodel, kn, kernel, mqarray, cellsize)
}

allhistcpp <- function(type, nc, jj, kk, mm, nmix, cumss, w, fi, li, gk, openval, cc, PIA, PIAJ, binomN, Tsk, intervals, moveargsi, CJSp1, movemodel, usermodel, kn, kernel, mqarray, cellsize, pmix) {
    .Call(`_openCR_allhistcpp`, type, nc, jj, kk, mm, nmix, cumss, w, fi, li, gk, openval, cc, PIA, PIAJ, binomN, Tsk, intervals, moveargsi, CJSp1, movemodel, usermodel, kn, kernel, mqarray, cellsize, pmix)
}

gethcpp <- function(nc1, cc, nmix, nk, jj, mm, PIA, cumss, Tsk, hk) {
    .Call(`_openCR_gethcpp`, nc1, cc, nmix, nk, jj, mm, PIA, cumss, Tsk, hk)
}

prwisecrmulticpp <- function(type, n, x, nc, jj, cumss, kk, mm, nmix, w, fi, li, hk, openval, cc, PIA, PIAJ, binomN, Tsk, intervals, moveargsi, h, hindex, CJSp1, movemodel, usermodel, kn, kernel, mqarray, cellsize) {
    .Call(`_openCR_prwisecrmulticpp`, type, n, x, nc, jj, cumss, kk, mm, nmix, w, fi, li, hk, openval, cc, PIA, PIAJ, binomN, Tsk, intervals, moveargsi, h, hindex, CJSp1, movemodel, usermodel, kn, kernel, mqarray, cellsize)
}

allhistmultcpp <- function(type, nc, jj, kk, mm, nmix, cumss, w, fi, li, hk, openval, cc, PIA, PIAJ, binomN, Tsk, intervals, h, hindex, CJSp1, moveargsi, movemodel, usermodel, kn, kernel, mqarray, cellsize, pmix) {
    .Call(`_openCR_allhistmultcpp`, type, nc, jj, kk, mm, nmix, cumss, w, fi, li, hk, openval, cc, PIA, PIAJ, binomN, Tsk, intervals, h, hindex, CJSp1, moveargsi, movemodel, usermodel, kn, kernel, mqarray, cellsize, pmix)
}

