# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gethcpp <- function(nc1, cc, nmix, nk, ss, mm, PIA, Tsk, hk) {
    .Call(`_openCR_gethcpp`, nc1, cc, nmix, nk, ss, mm, PIA, Tsk, hk)
}

makegkcpp <- function(cc, kk, mm, detectfn, sigmai, openval, traps, mask) {
    .Call(`_openCR_makegkcpp`, cc, kk, mm, detectfn, sigmai, openval, traps, mask)
}

makegkParallelcpp <- function(detectfn, sigmai, grain, openval, traps, mask) {
    .Call(`_openCR_makegkParallelcpp`, detectfn, sigmai, grain, openval, traps, mask)
}

makelookupcpp <- function(x) {
    .Call(`_openCR_makelookupcpp`, x)
}

PCH1cpp <- function(type, x, nc, jj, cumss, nmix, openval0, PIA0, PIAJ, intervals) {
    .Call(`_openCR_PCH1cpp`, type, x, nc, jj, cumss, nmix, openval0, PIA0, PIAJ, intervals)
}

PCH1secrcpp <- function(type, individual, x, nc, jj, cumss, kk, mm, openval0, PIA0, PIAJ, gk0, binomN, Tsk, intervals, moveargsi, movemodel, usermodel, kernel, mqarray, cellsize) {
    .Call(`_openCR_PCH1secrcpp`, type, individual, x, nc, jj, cumss, kk, mm, openval0, PIA0, PIAJ, gk0, binomN, Tsk, intervals, moveargsi, movemodel, usermodel, kernel, mqarray, cellsize)
}

PCH0secrjcpp <- function(type, x, nc, jj, cumss, kk, mm, cc0, PIA0, gk0, binomN, Tsk) {
    .Call(`_openCR_PCH0secrjcpp`, type, x, nc, jj, cumss, kk, mm, cc0, PIA0, gk0, binomN, Tsk)
}

PCH1secrparallelcpp <- function(x, type, grain, individual, jj, mm, nc, cumss, openval0, PIA0, PIAJ, gk0, binomN, Tsk, intervals, moveargsi, movemodel, kernel, mqarray, cellsize) {
    .Call(`_openCR_PCH1secrparallelcpp`, x, type, grain, individual, jj, mm, nc, cumss, openval0, PIA0, PIAJ, gk0, binomN, Tsk, intervals, moveargsi, movemodel, kernel, mqarray, cellsize)
}

pradelloglikcpp <- function(type, w, nc, jj, nmix, openval, PIAJ, intervals) {
    .Call(`_openCR_pradelloglikcpp`, type, w, nc, jj, nmix, openval, PIAJ, intervals)
}

prwicpp <- function(type, n, x, nc, jj, cumss, nmix, w, fi, li, openval, PIA, PIAJ, intervals, CJSp1) {
    .Call(`_openCR_prwicpp`, type, n, x, nc, jj, cumss, nmix, w, fi, li, openval, PIA, PIAJ, intervals, CJSp1)
}

allhistparallelcpp <- function(x, type, nc, CJSp1, grain, intervals, cumss, w, fi, li, openval, PIA, PIAJ) {
    .Call(`_openCR_allhistparallelcpp`, x, type, nc, CJSp1, grain, intervals, cumss, w, fi, li, openval, PIA, PIAJ)
}

prwisecrcpp <- function(type, n, x, nc, jj, kk, mm, nmix, cumss, w, fi, li, gk, openval, PIA, PIAJ, binomN, Tsk, intervals, moveargsi, h, hindex, CJSp1, movemodel, usermodel, kernel, mqarray, cellsize) {
    .Call(`_openCR_prwisecrcpp`, type, n, x, nc, jj, kk, mm, nmix, cumss, w, fi, li, gk, openval, PIA, PIAJ, binomN, Tsk, intervals, moveargsi, h, hindex, CJSp1, movemodel, usermodel, kernel, mqarray, cellsize)
}

allhistsecrparallelcpp <- function(x, type, mm, nc, binomN, CJSp1, grain, intervals, cumss, w, fi, li, gk, openval, PIA, PIAJ, Tsk, h, hindex, movemodel, moveargsi, kernel, mqarray, cellsize) {
    .Call(`_openCR_allhistsecrparallelcpp`, x, type, mm, nc, binomN, CJSp1, grain, intervals, cumss, w, fi, li, gk, openval, PIA, PIAJ, Tsk, h, hindex, movemodel, moveargsi, kernel, mqarray, cellsize)
}

